CREATE DATABASE IF  NOT EXISTS joaquim
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;
USE joaquim;

CREATE TABLE IF NOT EXISTS membros (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL,
setor VARCHAR(50) NOT NULL,
isadm BOOLEAN DEFAULT FALSE);



